language: node_js
node_js: "12.10.0"

#cache:

env:
  global:
    - DEBUG=off
    - NODE_ENV=production

os:
  - linux

before_install:
  - npm i -g electron-builder

install:
  - npm install

script:
  - npm test
  - npm run dist -- -mwl

deploy:
  provider: releases
  token: $GITHUB_PERSONAL_TOKEN
  file:
    - release/*.exe
    - release/*.dmg
    - release/*.deb
  cleanup: false
  on:
    tags: true

